spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cloud?autoReconnect=true"
    username: root
    password: "6ms2fT87UNvugs9qcjVgVvjDLrL98tFEo0yi5veZcWpRbf80JvjziDX1LNUZbs5GK0dZ1Hj9Xtrri2QnQJVMMucxTHAJLF88uy0v"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
jwt:
  secret-key: "A259724DFB5DDDB6C76A04C033890B970FFB3435FEFD5C08"
  validity-period: 7
  # validity-unit 时间单位，允许SECOND、MINUTE、HOUR、DAY
  validity-unit: "DAY"
  token-header: "Authorization"
  token-head: "Bearer "

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allowed-credentials: true

container:
  host: "unix:///var/run/docker.sock"
  registry-username: ""
  registry-password: ""
  registry-email: ""
  registry-url: ""
  max-connections: 100
  connection-timeout: 30
  connection-timeout-unit: SECOND
  response-timeout: 45
  response-timeout-unit: SECOND
  auto-flush: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%clr(%-5level)] %clr(%-15.15logger){cyan}：%msg%n"